
version: 2

models:
  - name: transactions_model
    description: "Transaction models"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
